import type { Metadata } from 'next';
import Link from 'next/link';
import { ArticlePage } from '@/components/ArticlePage';
import { TableOfContents } from '@/components/TableOfContents';
import { pageMetadata } from '@/lib/seo';

const title='İndi Bindi Ücreti Nedir?';
const description='İndi bindi olarak bilinen minimum taksi ücretinin ne zaman uygulandığını, kilometre eşiğinin nasıl hesaplandığını ve yanlış bilinenleri örneklerle öğrenin.';
const path='/indi-bindi-ucreti-nedir/';
const faqs=[
  {question:'İndi bindi ücreti her taksi yolculuğunda alınır mı?',answer:'Hayır. Yalnızca açılış, mesafe ve varsa zaman hesabı şehirdeki minimum ücretin altında kaldığında alt sınır olarak uygulanır. Hesap minimumu aşarsa normal taksimetre tutarı geçerlidir.'},
  {question:'İndi bindi ücreti taksimetreye ayrıca eklenir mi?',answer:'Hayır. Minimum ücret normal tutarın üzerine eklenen ikinci bir kalem değildir. Düşük kalan taksimetre hesabını belirlenen alt sınıra tamamlar.'},
  {question:'Minimum ücret kaç kilometreye kadar geçerlidir?',answer:'Tek bir Türkiye geneli kilometre sınırı yoktur. Yaklaşık eşik, minimum ücretten açılış bedelinin çıkarılıp kilometre ücretine bölünmesiyle bulunabilir; bekleme bedeli varsa eşik değişir.'},
  {question:'Gece indi bindi ücreti farklı mıdır?',answer:'Yalnızca yerel tarife kararında ayrı bir gece tarifesi yayımlanmışsa farklı olabilir. Kaynakta bulunmayan bir gece katsayısı varsayılmamalıdır.'},
];

export const metadata:Metadata=pageMetadata(title,description,path,'article');

export default function MinimumFareGuide(){return <ArticlePage title={title} description={description} path={path} modified="2026-07-16" category="Taksi Rehberleri" readingMinutes={8} faqs={faqs}>
  <p className="notice"><strong>İndi bindi ücreti</strong>, kısa taksi yolculuklarında uygulanan minimum ödeme sınırıdır. Taksimetrede oluşan normal ücret bu sınırın altında kaldığında minimum tutar ödenir; yolculuk bedelinin üzerine ayrıca eklenmez.</p>
  <p>Günlük dilde “indi bindi” denilse de resmî tarife belgelerinde “minimum ücret”, “kısa mesafe ücreti” veya “yolculuk başına minimum ücret” gibi ifadeler görülebilir. Mantık aynıdır: çok kısa bir yolculuğun alt ödeme sınırını belirlemek.</p>
  <TableOfContents items={[{id:'uygulama',label:'Minimum ücret ne zaman uygulanır?'},{id:'esik',label:'Kilometre eşiği nasıl bulunur?'},{id:'ornekler',label:'Kısa ve uzun yolculuk örnekleri'},{id:'yanlislar',label:'Sık yapılan yanlışlar'},{id:'sehir-farki',label:'Neden şehirden şehre değişir?'},{id:'kontrol',label:'Güncel minimum ücret nasıl kontrol edilir?'},{id:'sik-sorulan-sorular',label:'Sık sorulan sorular'}]}/>

  <section id="uygulama"><h2>Minimum ücret ne zaman uygulanır?</h2><p>Taksimetrenin açılış ve mesafe üzerinden hesapladığı tutar, yerel tarifedeki minimum sınırdan düşükse minimum ücret uygulanır. Bekleme veya düşük hız bedeli tarifede yer alıyorsa bu kalem de ara toplamı etkileyebilir.</p><p>Örneğin normal hesap 175 TL, şehirdeki minimum ücret 200 TL ise ödenecek taksimetre tabanı 200 TL olur. Normal hesap 245 TL’ye ulaştığında ise 200 TL ayrıca eklenmez; sonuç 245 TL üzerinden devam eder.</p></section>

  <section id="esik"><h2>İndi bindi kilometre eşiği nasıl bulunur?</h2><p>Bekleme ve ek ücret yokken yaklaşık eşik şu formülle bulunabilir:</p><p className="notice"><strong>Yaklaşık kilometre eşiği = (minimum ücret − açılış bedeli) ÷ kilometre bedeli</strong></p><p>Örnek bir tarifede açılış 65 TL, kilometre bedeli 40 TL ve minimum ücret 200 TL olsun. Hesap şöyle yapılır: (200 − 65) ÷ 40 = 3,375 km. Bu örnekte açılış ve mesafe hesabı yaklaşık 3,38 km civarında minimum ücrete ulaşır.</p><p>Bu rakam “ilk 3,38 km her koşulda sabit fiyat” anlamına gelmez. Bekleme bedeli, farklı araç kategorisi veya tarife ölçüm aralıkları eşiği değiştirebilir.</p></section>

  <section id="ornekler"><h2>Kısa ve uzun yolculuk örnekleri</h2><div className="table-wrap"><table><thead><tr><th>Durum</th><th>Normal hesap</th><th>Minimum</th><th>Uygulanan taban</th></tr></thead><tbody><tr><th scope="row">Çok kısa rota</th><td>150 TL</td><td>200 TL</td><td>200 TL</td></tr><tr><th scope="row">Eşiğe yakın rota</th><td>198 TL</td><td>200 TL</td><td>200 TL</td></tr><tr><th scope="row">Daha uzun rota</th><td>260 TL</td><td>200 TL</td><td>260 TL</td></tr></tbody></table></div><p>Tablodaki rakamlar yöntemi göstermek içindir. Güncel tutarı görmek için <Link href="/">şehir seçerek hesaplama yapın</Link> veya <Link href="/sehirler/">yayımlanmış şehir sayfalarını</Link> inceleyin.</p></section>

  <section id="yanlislar"><h2>İndi bindi hakkında sık yapılan yanlışlar</h2><h3>“Açılış + minimum ücret birlikte alınır”</h3><p>Yanlış. Açılış bedeli normal hesabın içindedir. Minimum ücret, bu hesabın ulaşması gereken alt sınırdır.</p><h3>“Minimum ücret Türkiye’nin her yerinde aynıdır”</h3><p>Yanlış. Açılış, kilometre ve minimum tutarlar yerel kararlarla değişir. Aynı yıl içinde şehirlerin güncelleme tarihleri de farklı olabilir.</p><h3>“Kısa mesafeye taksi gitmezse ücret kuralıdır”</h3><p>Minimum ücret bir fiyatlandırma kuralıdır; hizmetin kabulüyle ilgili ayrı sorunları açıklamaz. Yaşanan olayı plaka, tarih, saat ve konum bilgisiyle ilgili belediye kanalına bildirmek daha sağlıklı olur.</p><h3>“Minimum ücret sabit paket fiyattır”</h3><p>Taksimetre hesabı minimumu geçtiği anda normal tarife işlemeye devam eder. Bu nedenle indi bindi, belirli bir semte kadar geçerli pazarlık fiyatı değildir.</p></section>

  <section id="sehir-farki"><h2>Neden şehirden şehre değişir?</h2><p>Taksi tarifeleri yerel ulaşım kararları ve yetkili kurumların yayımladığı çizelgelerle belirlenir. Maliyetler, araç kategorileri, hizmet alanı ve karar tarihleri aynı olmadığı için Türkiye genelinde tek bir minimum tutar bulunmaz.</p><p>İstanbul’da birden fazla taksi kategorisi için ayrı minimum ücretler bulunabilirken başka bir şehirde yalnızca standart veya merkez taksi tarifesi yayımlanabilir. Bu nedenle yalnızca “2026 indi bindi ücreti” diye aranan tek bir rakamı bütün şehirlere uygulamak doğru değildir.</p></section>

  <section id="kontrol"><h2>Güncel minimum ücret nasıl kontrol edilir?</h2><ol><li>Şehir sayfasındaki yürürlük ve son doğrulama tarihine bakın.</li><li>Tarife tablosunda kullandığınız araç kategorisini kontrol edin.</li><li>Bağlantısı verilen belediye, UKOME veya yetkili kurum belgesini açın.</li><li>Eski haberlerdeki rakam yerine en yeni yürürlük tarihini esas alın.</li><li>Belge ile hesaplayıcı farklıysa <Link href="/iletisim/">kaynak bağlantısıyla düzeltme bildirin</Link>.</li></ol><p><a href="https://tuhim.ibb.gov.tr/ucret-tarifeler/" rel="external">İBB TUHİM ücret tarifeleri</a>, resmî bir tarife arşivinin nasıl yayımlandığına örnektir. Genel trafik mevzuatında taksi otomobillerinde taksimetre bulundurma zorunluluğunu <a href="https://www.mevzuat.gov.tr/mevzuatmetin/1.5.2918.pdf" rel="external">2918 sayılı Karayolları Trafik Kanunu</a> üzerinden inceleyebilirsiniz.</p><p>Tarife kayıtlarının hangi kaynaklarla değerlendirildiğini <Link href="/veri-kaynaklari-ve-hesaplama-yontemi/">veri kaynakları ve hesaplama yönteminde</Link> okuyabilirsiniz. Minimum ücret, kısa yolculuğu anlamayı kolaylaştıran basit bir alt sınırdır. Karmaşa genellikle bu sınırın normal ücrete eklenen ayrı bir bedel sanılmasından doğar.</p></section>
</ArticlePage>}
