import type { Metadata } from 'next';
import Link from 'next/link';
import { ArticlePage } from '@/components/ArticlePage';
import { TableOfContents } from '@/components/TableOfContents';
import { pageMetadata } from '@/lib/seo';

const title='İndi Bindi Ücreti Nedir?';const description='İndi bindi olarak bilinen minimum taksi ücretinin kısa yolculuklarda ne zaman uygulandığını, nasıl kontrol edildiğini ve ne olmadığını öğrenin.';const path='/indi-bindi-ucreti-nedir/';
export const metadata:Metadata=pageMetadata(title,description,path,'article');
export default function MinimumFareGuide(){return <ArticlePage title={title} description={description} path={path} modified="2026-07-16" category="Taksi Rehberleri" readingMinutes={4}><p className="notice">İndi bindi, kısa yolculuk için belirlenen minimum ücrettir. Her hesaba ayrıca eklenen bir ceza veya ikinci açılış bedeli değildir.</p><TableOfContents items={[{id:'uygulama',label:'Minimum ücret ne zaman uygulanır?'},{id:'ek-ucret',label:'Ayrı bir ek ücret midir?'},{id:'sehir-farki',label:'Neden şehirden şehre değişir?'},{id:'kontrol',label:'Nasıl kontrol edilir?'}]}/><section id="uygulama"><h2>Minimum ücret ne zaman uygulanır?</h2><p>Açılış ve gidilen yol için oluşan tutar şehirde belirlenen alt sınırın altında kalırsa minimum yolculuk ücreti geçerli olur. Hesap alt sınırı aşarsa normal taksimetre tutarı ödenir.</p></section><section id="ek-ucret"><h2>Ayrı bir ek ücret midir?</h2><p>Hayır. Minimum ücret, hesaplanan düşük tutarın tamamlandığı alt sınırdır. Normal yolculuk bedelinin üzerine ikinci kez eklenmez.</p></section><section id="sehir-farki"><h2>Neden şehirden şehre değişir?</h2><p>Açılış, kilometre ve minimum ücret yerel tarife kararlarıyla belirlenir. Türkiye geneli tek bir indi bindi tutarı yoktur.</p></section><section id="kontrol"><h2>Nasıl kontrol edilir?</h2><p><Link href="/">Ana hesaplayıcıdan</Link> şehrinizi seçin veya <Link href="/sehirler/">yayımlanmış şehir rehberini</Link> açın. Güvenilir tarife bulunmayan şehirlerde site tutar göstermez.</p></section></ArticlePage>}
