import type { Metadata } from 'next';
import Link from 'next/link';
import { ArticlePage } from '@/components/ArticlePage';
import { TableOfContents } from '@/components/TableOfContents';
import { pageMetadata } from '@/lib/seo';

const title='Taksi Ücreti Nasıl Hesaplanır?';
const description='Taksi ücretinin açılış, kilometre, minimum ücret, bekleme ve ücretli geçişlerle nasıl hesaplandığını formül ve gerçekçi örneklerle öğrenin.';
const path='/taksi-ucreti-nasil-hesaplanir/';
const faqs=[
  {question:'Taksi ücreti hesaplama formülü nedir?',answer:'Temel hesap açılış bedeli ile kilometre bedelinin toplamıdır. Varsa bekleme bedeli eklenir, sonuç minimum ücretin altında kalıyorsa minimum ücret uygulanır; köprü, tünel ve otoyol gibi ek geçişler en son eklenir.'},
  {question:'Trafikte beklemek taksi ücretini artırır mı?',answer:'Şehrin yayımlanmış tarifesinde zaman veya bekleme bedeli varsa araç düşük hızda ilerlerken ya da beklerken taksimetre artabilir. Uygulamanın teknik eşiği ve geçiş biçimi taksimetre tarifesine göre değişebilir.'},
  {question:'Haritadaki tahmin neden taksimetreden farklı çıkar?',answer:'Harita rotası, gerçek dönüşler, yol çalışmaları, trafik, bırakma noktası, araç kategorisi ve ücretli geçişler değişebilir. Hesaplayıcı bu nedenle planlama tahmini verir, sabit fiyat garanti etmez.'},
  {question:'İndi bindi ücreti normal tutara ayrıca eklenir mi?',answer:'Hayır. İndi bindi olarak bilinen minimum ücret, hesaplanan tutar düşük kaldığında uygulanan alt sınırdır. Normal taksimetre tutarının üzerine ikinci kez eklenmez.'},
];

export const metadata:Metadata=pageMetadata(title,description,path,'article');

export default function FareGuide(){return <ArticlePage title={title} description={description} path={path} modified="2026-07-16" category="Taksi Rehberleri" readingMinutes={9} faqs={faqs}>
  <p className="notice"><strong>Kısa cevap:</strong> Taksi ücreti; açılış bedeli, gidilen yol, varsa düşük hız veya bekleme bedeli ve ücretli geçişlerden oluşur. Hesaplanan ara toplam şehrin minimum ücretinden düşükse yolcu minimum ücreti öder.</p>
  <p>Bir taksi tahminini doğru yorumlamak için “kilometre × fiyat” işlemi tek başına yeterli değildir. Şehir tarifesi, araç kategorisi ve gerçek rota aynı anda değerlendirilmelidir. Aşağıdaki yöntem, hesaplayıcının kullandığı mantığı adım adım açıklar.</p>
  <TableOfContents items={[{id:'formul',label:'Taksi ücreti hesaplama formülü'},{id:'kalemler',label:'Ücreti oluşturan kalemler'},{id:'ornek',label:'Adım adım örnek hesap'},{id:'mesafe',label:'Doğru mesafe nasıl seçilir?'},{id:'bekleme',label:'Bekleme ve düşük hız'},{id:'gecisler',label:'Köprü, tünel ve otoyol'},{id:'kontrol',label:'Sonucu nasıl kontrol edebilirsiniz?'},{id:'sik-sorulan-sorular',label:'Sık sorulan sorular'}]}/>

  <section id="formul"><h2>Taksi ücreti hesaplama formülü</h2><p>Basitleştirilmiş hesap şu sırayla yapılır:</p><ol><li><strong>Mesafe tutarı</strong> = açılış bedeli + (gidilen kilometre × kilometre bedeli)</li><li><strong>Ara toplam</strong> = mesafe tutarı + varsa bekleme bedeli</li><li><strong>Taksimetre tabanı</strong> = ara toplam ile minimum ücretin yüksek olanı</li><li><strong>Tahmini toplam</strong> = taksimetre tabanı + köprü, tünel, otoyol ve diğer doğrulanmış ekler</li></ol><p>Bu formül fiyatın hangi parçadan yükseldiğini anlamayı kolaylaştırır. Taksimetrenin teknik çalışma biçimi ve düşük hız eşiği cihazdaki onaylı tarifeye bağlıdır.</p></section>

  <section id="kalemler"><h2>Ücreti oluşturan kalemler</h2><h3>Açılış bedeli</h3><p>Araç yolculuğa başladığında taksimetrede görülen başlangıç tutarıdır. Aynı şehirde farklı taksi kategorileri varsa her kategorinin açılış bedeli farklı olabilir.</p><h3>Kilometre bedeli</h3><p>Araç ilerledikçe mesafeye göre eklenen tutardır. Navigasyondaki kuş uçuşu uzaklık değil, aracın gerçekten kullanacağı yol uzunluğu önemlidir.</p><h3>Minimum ücret</h3><p>Kısa yolculuklarda ödenecek alt sınırdır. Açılış ve kilometre hesabı bu sınırın altında kalırsa sonuç minimum ücrete tamamlanır. Ayrıntılı örnekler için <Link href="/indi-bindi-ucreti-nedir/">indi bindi ücreti rehberine</Link> bakabilirsiniz.</p><h3>Bekleme veya zaman bedeli</h3><p>Bazı tarifelerde araç beklediğinde ya da belirli bir hızın altında ilerlediğinde zaman tarifesi devreye girer. Şehir kaynağında bu bedel yayımlanmamışsa tahmine hayalî bir bekleme ücreti eklenmemelidir.</p></section>

  <section id="ornek"><h2>Adım adım örnek hesap</h2><p>Aşağıdaki rakamlar yalnızca yöntemi göstermek için oluşturulmuş örnektir; belirli bir şehrin güncel tarifesi değildir.</p><div className="table-wrap"><table><thead><tr><th>Kalem</th><th>Örnek değer</th><th>Hesap</th></tr></thead><tbody><tr><th scope="row">Açılış</th><td>60 TL</td><td>60 TL</td></tr><tr><th scope="row">Mesafe</th><td>3 km × 35 TL</td><td>105 TL</td></tr><tr><th scope="row">Ara toplam</th><td>Açılış + mesafe</td><td>165 TL</td></tr><tr><th scope="row">Minimum ücret</th><td>190 TL</td><td>165 TL düşük kaldığı için 190 TL</td></tr><tr><th scope="row">Ücretli geçiş</th><td>Yok</td><td>0 TL</td></tr></tbody></table></div><p>Bu örnekte 3 km için matematiksel mesafe hesabı 165 TL olsa da minimum sınır 190 TL olduğu için tahmini yolculuk bedeli 190 TL olur. Mesafe uzadığında açılış + kilometre hesabı minimumu geçer ve normal tarife üzerinden ilerler.</p></section>

  <section id="mesafe"><h2>Doğru mesafe nasıl seçilir?</h2><p>Haritada başlangıç ve varış noktasını mümkün olduğunca kesin işaretleyin. Büyük bir otel, hastane, terminal veya alışveriş merkezinde farklı girişler yüzlerce metre, bazen daha fazla fark yaratabilir.</p><ul><li>Kuş uçuşu uzaklığı kullanmayın.</li><li>Tek yön, dönüş yasağı ve yol çalışması bulunan rotaları kontrol edin.</li><li>Harita iki rota sunuyorsa kısa ve hızlı rotayı ayrı ayrı hesaplayın.</li><li>Havalimanında terminal girişini, şehir içinde gerçek bırakma noktasını seçin.</li></ul><p>Örneğin bir rota 12 km, alternatif rota 15 km görünüyorsa tek bir “kesin” tutar yerine iki mesafeyi de hesaplamak daha yararlı bir bütçe aralığı verir.</p></section>

  <section id="bekleme"><h2>Bekleme ve düşük hız ücreti nasıl etkiler?</h2><p>Yoğun trafikte araç çok yavaş ilerlediğinde taksimetre yalnızca mesafeye göre davranmayabilir. Onaylı tarifede zaman bedeli varsa düşük hızda geçen süre toplamı artırır. Bu nedenle aynı 10 km rota, akıcı trafikte ve yoğun saatte farklı tutabilir.</p><p>Bekleme süresini tahmin ederken bütün yolculuk süresini değil, olağan sürüşün üzerindeki belirgin durma veya düşük hız süresini düşünün. Aksi hâlde kilometre hesabıyla zaten temsil edilen normal sürüş süresini iki kez sayabilirsiniz.</p></section>

  <section id="gecisler"><h2>Köprü, tünel ve otoyol bedelleri</h2><p>Ücretli geçişler çoğu zaman temel taksi tarifesinden ayrı değerlendirilir. Geçiş kullanılacaksa güncel bedeli ve rotayı sürücüyle yolculuk başlamadan konuşun. Özellikle İstanbul’da köprü veya Avrasya Tüneli tercihi hem mesafeyi hem de eklenecek geçiş tutarını değiştirebilir.</p><p>Geçiş ücretleri sık değişebildiği için eski bir blog tablosunu kopyalamak yerine ilgili işletmenin veya kamu kurumunun güncel tarifesini kontrol edin. Hesaplayıcıdaki “ek yol ücreti” alanı bu tutarı temel tahminden ayrı tutar.</p></section>

  <section id="kontrol"><h2>Sonucu nasıl kontrol edebilirsiniz?</h2><ol><li><Link href="/">Ana taksi ücreti hesaplayıcısında</Link> şehri seçin.</li><li>Yayımlanmış kategori varsa araç türünü doğru işaretleyin.</li><li>Güncel araç rotası mesafesini girin.</li><li>Bekleme ve ücretli geçişleri yalnızca gerçekten bekleniyorsa ekleyin.</li><li>Sonucu şehir sayfasındaki kaynak tarihiyle karşılaştırın.</li></ol><p>Taksi otomobillerinde taksimetre bulundurulması ve kullanılabilir durumda olması, <a href="https://www.mevzuat.gov.tr/mevzuatmetin/1.5.2918.pdf" rel="external">2918 sayılı Karayolları Trafik Kanunu</a> kapsamında düzenlenir. Bir tarife veya hizmet sorunu için belediyenin ulaşım birimine ya da <a href="https://www.turkiye.gov.tr/sikayet-ve-bilgi-edinme-hizmetleri" rel="external">e-Devlet şikâyet ve bilgi edinme hizmetlerine</a> başvurabilirsiniz.</p><p>Unutmayın: Hesaplayıcı bütçe planlamasına yardımcı olur; kesin bedel gerçek rota ve geçerli taksimetre üzerinden oluşur.</p></section>
</ArticlePage>}
