import type { Metadata } from 'next';
import Link from 'next/link';
import { ArticlePage } from '@/components/ArticlePage';
import { TableOfContents } from '@/components/TableOfContents';
import { pageMetadata } from '@/lib/seo';

const title='Taksi Ücreti Nasıl Hesaplanır?';
const description='Taksi ücretinde açılış, mesafe, minimum ücret, bekleme ve ücretli geçişlerin rolünü; doğru mesafe seçimini ve tahmin sınırlarını öğrenin.';
const path='/taksi-ucreti-nasil-hesaplanir/';
export const metadata:Metadata=pageMetadata(title,description,path,'article');
export default function FareGuide(){return <ArticlePage title={title} description={description} path={path} modified="2026-07-16" category="Taksi Rehberleri" readingMinutes={5}><p className="notice">Kısa cevap: Taksimetre açılış bedeliyle başlar, gidilen yol ve varsa doğrulanmış zaman bedeliyle ilerler. Hesap minimum sınırın altında kalırsa şehirdeki minimum yolculuk ücreti uygulanır.</p><TableOfContents items={[{id:'kalemler',label:'Ücreti oluşturan kalemler'},{id:'mesafe',label:'Doğru mesafe nasıl seçilir?'},{id:'bekleme',label:'Bekleme ve düşük hız'},{id:'gecisler',label:'Köprü, tünel ve otoyol'},{id:'fark',label:'Tahmin neden farklı olabilir?'}]}/><section id="kalemler"><h2>Ücreti oluşturan kalemler</h2><p>Açılış bedeli yolculuğun başlangıcında görünür. Araç ilerledikçe şehrin kilometre tarifesi taksimetreye yansır. Kısa yolculukta hesaplanan tutar alt sınırın altında kalırsa minimum ücret geçerli olur.</p><p><Link href="/">Ana hesaplayıcı</Link> bu kalemleri sonuçta ayrı gösterir.</p></section><section id="mesafe"><h2>Doğru mesafe nasıl seçilir?</h2><p>Haritadaki kuş uçuşu uzaklığı değil, araçla gidilecek yaklaşık yol uzunluğunu kullanın. Tek yönler, dönüş yasakları, çalışmalar ve tercih edilen güzergâh mesafeyi değiştirebilir.</p></section><section id="bekleme"><h2>Bekleme ve düşük hız</h2><p>Bazı şehir tarifelerinde araç belirli bir hızın altına indiğinde zaman bedeli devreye girer. Site yalnızca yayımlanmış saatlik tarife bulunduğunda bekleme alanını açar.</p></section><section id="gecisler"><h2>Köprü, tünel ve otoyol</h2><p>Ücretli geçişler taksi tarifesinden ayrı olabilir. Yalnızca gerçekten kullanılacak geçişi ekleyin ve güzergâhı sürücüyle netleştirin.</p></section><section id="fark"><h2>Tahmin neden farklı olabilir?</h2><p>Gerçek rota, trafikte geçen süre, araç kategorisi, geçişler ve yeni tarife kararları sonucu değiştirebilir. Kesin tutarı geçerli taksimetre belirler.</p></section></ArticlePage>}
