import type { Metadata } from 'next';
import Link from 'next/link';
import { ArticlePage } from '@/components/ArticlePage';
import { Calculator } from '@/components/Calculator';
import { TableOfContents } from '@/components/TableOfContents';
import { fare, formatDate, money, publishedCities } from '@/src/data/cities';
import { pageMetadata } from '@/lib/seo';

const city=publishedCities.find((item)=>item.slug==='istanbul')!;const routes=[['Taksim',42],['Sultanahmet',47],['Beşiktaş',44],['Kadıköy',60],['Sabiha Gökçen Havalimanı',80]] as const;const title='İstanbul Havalimanı Taksi Ücreti 2026';const description='İstanbul Havalimanı taksi ücretini güncel İstanbul tarifesiyle hesaplayın; taksi kategorileri, rota, trafik ve ücretli yol etkisini inceleyin.';const path='/istanbul-havalimani-taksi-ucreti/';
export const metadata:Metadata=pageMetadata(title,description,path,'article');
export default function IstanbulAirport(){return <ArticlePage title={title} description={description} path={path} modified={city.verifiedDate} category="Havalimanı Taksi Ücretleri" readingMinutes={5}><p className="notice">Havalimanı için sabit fiyat yoktur. Haritanızdaki güncel mesafeyi ve olası ücretli yol bedelini hesaplayıcıya girin.</p><TableOfContents items={[{id:'hesaplama',label:'Havalimanı taksi hesaplama'},{id:'rotalar',label:'Popüler varış noktaları'},{id:'hazirlik',label:'Taksiye binmeden önce'},{id:'kaynak',label:'Tarife dayanağı'}]}/><section id="hesaplama"><h2>İstanbul Havalimanı taksi hesaplama</h2><Calculator fixedCity="istanbul"/></section><section id="rotalar"><h2>Popüler varış noktaları</h2><div className="table-wrap"><table><thead><tr><th>Varış</th><th>Örnek mesafe</th><th>Beklemesiz sarı taksi tahmini</th></tr></thead><tbody>{routes.map(([name,km])=><tr key={name}><th scope="row">{name}</th><td>{km} km</td><td>{money(fare(city,km).total)}</td></tr>)}</tbody></table></div><p>Mesafeler yaklaşık örnektir; başlangıç kapısı, rota, trafik ve ücretli geçişler sonucu değiştirir.</p></section><section id="hazirlik"><h2>Taksiye binmeden önce</h2><ol><li>Terminaldeki resmî taksi alanını kullanın.</li><li>Taksi kategorisini ve taksimetrenin açıldığını kontrol edin.</li><li>Ücretli yol tercihini sürücüyle netleştirin.</li><li>Uçuş bağlantınız varsa trafik için ek süre bırakın.</li></ol><p><Link href="/istanbul-taksi-ucreti/">İstanbul şehir tarifesini</Link> inceleyebilirsiniz.</p></section><section className="source-box" id="kaynak"><h2>Tarife dayanağı</h2><p>Hesaplar <time dateTime={city.effectiveDate}>{formatDate(city.effectiveDate)}</time> tarihinden geçerli İBB TUHİM taksi tarifesini kullanır.</p><a href={city.sourceUrl} rel="external">İBB tarife belgesi</a></section></ArticlePage>}
